export const LOG_CREATE_REQUEST = 'LOG_CREATE_REQUEST'
export const LOG_CREATE_SUCCESS = 'LOG_CREATE_SUCCESS'
export const LOG_CREATE_FAIL = 'LOG_CREATE_FAIL'

export const LOG_LIST_REQUEST = 'LOG_LIST_REQUEST'
export const LOG_LIST_SUCCESS = 'LOG_LIST_SUCCESS'
export const LOG_LIST_FAIL = 'LOG_LIST_FAIL'